name: prod api helm deployment
permissions: write-all

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest  # Using the default GitHub runner
    steps:
      - name: Print Hello World from Build Job
        run: echo "Hello World from Build Job"

      - name: Print Runner ID from Build Job
        run: echo "Runner ID ${{ runner.id }}"

      - name: Print GitHub Run ID
        run: echo "GitHub Run ID ${{ github.run_id }}"

  deploy-helm:
    runs-on: ubuntu-latest  # Using the default GitHub runner for testing
    needs: build-docker  # Job 2 waits for Job 1 to complete before executing
    steps:
      - name: Print Hello World from Deploy Job
        run: echo "Hello World from Deploy Job"

      - name: Print Runner ID from Deploy Job
        run: echo "Runner ID ${{ runner.id }}"

      - name: Print GitHub Run ID
        run: echo "GitHub Run ID ${{ github.run_id }}"
